version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd server && npm install -g yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
artifacts:
  files:
    - '**/*'