version: 0.2

phases:
  install:
    runtime-versions:
      nodejs:18
    commands:
      - cd server && npm install -g pnpm
    pre_build:
      - pnpm install
    build:
      commands:
        - pnpm build
artifacts:
  files:
    - '**/*'